default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') { 'password' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  port: <%= ENV.fetch('DATABASE_PORT') { 5432 } %>

development:
  <<: *default
  database: <%= ENV.fetch("MYSQL_DATABASE") { 'app_development' } %>

test:
  <<: *default
  host: <%= ENV.fetch('TEST_DATABASE_HOST') { 'localhost' } %>
  database: <%= ENV.fetch("MYSQL_DATABASE") { 'app_test' } %>

production:
  <<: *default
  database: app_production